apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - 8bdecb1a.alexellis.io
    verbs:
      - get
      - create
      - update
      - patch